---
org:
  groups:
    'group1':
      state: 'present'
    'group2':
      state: 'present'
  users:
    - name: 'user1'
      state: 'present'
      comment: 'User1'
      createhome: true
      groups:
        - group1
        - group2
      home: '/home/user1'
      shell: '/bin/bash'
      password_max_age: '99999'
      authorized_keys:
       - 'ssh-rsa <ssh-key> user@host'
  sudogroup: 'group1'
